[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'ryvm'
version = '0.1.0'

[dependencies]
rodio = '*'
once_cell = '*'
itertools = '*'
structopt = { version = '*', default-features = false }
piston_window = { version = '*', optional = true }
outsource = { path = '../outsource' }
tinymap = { path = '../tinymap' }
find_folder = '*'
midir = '*'
send_wrapper = '*'
crossbeam-utils = '*'
rand = "*"

[features]
default = []
keyboard = ['piston_window']
