[dependencies]
rodio = '*'
crossbeam = '*'
once_cell = "*"
unicode_reader = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
indexmap = {  version = "*", features = ["serde-1"] }
itertools = "*"
structopt = { version = "*", default-features = false }
piston_window = { version = "*", optional = true }

[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'album'
version = '0.1.0'

[features]
default = ["keyboard"]
keyboard = ["piston_window"]
